# Generated by Django 3.2.18 on 2023-04-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('management', 'management'), ('support', 'support'), ('sale', 'sale')], max_length=50, null=True),
        ),
    ]
