# Generated by Django 3.2.18 on 2023-04-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('management', 'management'), ('support', 'support'), ('sale', 'sale')], default='sale', max_length=50),
        ),
    ]
