# Generated by Django 3.2.18 on 2023-04-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
